---
title: "Bourdons, the way to go!"
author: "Elisa Pellegrino"
date: "10/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
```

```{r}
?readxl::read_excel
```


```{r import 2}
bourdon_2 <- read("./data/etho_tp2.xlsx" , type = "xlsx")

```

```{r}
ouvri <- read("./data/que_ouvri.xlsx")
```

##TEST DE STUDENT MASSE CELLULE RADIALE

```{r}
t.test(bourdon_2$weight,
  alternative = "two.sided", mu = 0, conf.level = 0.95)
```


```{r}
t.test(bourdon_2$size_cr,
  alternative = "two.sided", mu = 0, conf.level = 0.95)
```

##TEST DE CORRELATION
```{r}
cor.test(data = bourdon_2, ~ weight + size_cr, alternative = "greater")
```

##REGRESSION LINEAIRE 

### REINE+OUVRIERE
```{r}
(lm. <- lm(data = bourdon_2, weight ~ size_cr))
summary(lm.)
```

### Interpretation graphique
```{r}
lm. %>.% (function(lm, model = lm[["model"]], vars = names(model))
  chart(model, aes_string(x = vars[2], y = vars[1])) +
  geom_point() +
  stat_smooth(method = "lm", formula = y ~ x))(.)+
  labs(y = "Masse (g)", x = "Taille de la cellule radiale (mm)") 
```



### Residuals vs fitted 
```{r}
lm. %>.%
  chart(broom::augment(.), .resid ~ .fitted) +
  geom_point() +
  geom_hline(yintercept = 0) +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x) +
  labs(x = "Fitted values", y = "Residuals") +
  ggtitle("Residuals vs Fitted")
```


###Normal Q-Q
```{r}
lm. %>.%
  chart(broom::augment(.), aes(sample = .std.resid)) +
  geom_qq() +
  geom_qq_line(colour = "darkgray") +
  labs(x = "Theoretical quantiles", y = "Standardized residuals") +
  ggtitle("Normal Q-Q")
```

### Scale location
```{r}
lm. %>.%
  chart(broom::augment(.), sqrt(abs(.std.resid)) ~ .fitted) +
  geom_point() +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x) +
  labs(x = "Fitted values",
    y = expression(bold(sqrt(abs("Standardized residuals"))))) +
  ggtitle("Scale-Location")
```

###OUVRIERES
```{r}
(lm1. <- lm(data = ouvri, weight ~ size_cr))
summary(lm1.)
```
### Interpretation graphique
```{r}
lm1. %>.% (function(lm, model = lm[["model"]], vars = names(model))
  chart(model, aes_string(x = vars[2], y = vars[1])) +
  geom_point() +
  stat_smooth(method = "lm", formula = y ~ x))(.)+
  labs(y = "Masse (g)", x = "Taille de la cellule radiale (mm)") 
```

### Residuals vs fitted
```{r}
lm1. %>.%
  chart(broom::augment(.), .resid ~ .fitted) +
  geom_point() +
  geom_hline(yintercept = 0) +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x) +
  labs(x = "Fitted values", y = "Residuals") +
  ggtitle("Residuals vs Fitted")
```

### Normal Q-Q
```{r}
lm1. %>.%
  chart(broom::augment(.), aes(sample = .std.resid)) +
  geom_qq() +
  geom_qq_line(colour = "darkgray") +
  labs(x = "Theoretical quantiles", y = "Standardized residuals") +
  ggtitle("Normal Q-Q")
```

### Scale location
```{r}
lm1. %>.%
  chart(broom::augment(.), sqrt(abs(.std.resid)) ~ .fitted) +
  geom_point() +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x) +
  labs(x = "Fitted values",
    y = expression(bold(sqrt(abs("Standardized residuals"))))) +
  ggtitle("Scale-Location")
```

